### ISSUE TITLE
Altoholic Classic defunct?

### ISSUE THREAD

**Issue by rbpaiett** [teelolws/LibGatheringNodes#2]
Sry, didn't know how to contact you by any other means.  Are you no longer working on the Altoholic Classic addon?

**Comment by teelolws** [comment]
Thaoky has been very hostile about the situation and I've decided I'd rather not deal with him anymore. He has obtained my personal details from Github and I'd rather he doesn't escalate the issue to unreasonable levels. So I'm no longer publicly sharing my fork of the addon anymore.

![image](https://user-images.githubusercontent.com/49792789/117588617-87f36800-b178-11eb-886d-8414ff73dde4.png)

**Comment by jrubimf** [comment]
Why did you do the whole loadstring bullshit?

I don't answer to you.
